Add placeholders for input fields in sign-up component
rochagbriel/AlterEgoAdventures pull request #12
Opened 2024-01-31 20:00 UTC by rochagbriel

2024-02-01 09:06 UTC, ttobollik requested changes
Well done! A little bit of minor feedback only :)

2024-02-01 17:57 UTC, rochagbriel commented on src/app/sign-up/sign-up.component.html
> +        placeholder="Enter your last name"
done!

2024-02-01 18:02 UTC, rochagbriel commented on src/app/sign-up/sign-up.component.html
> +        placeholder="Enter your first name"
I couldn't style the option. I tried a few solutions, but they didn't work.

2024-02-02 08:23 UTC, ttobollik approved these changes
Well done. Thanks!

2024-02-02 13:48 UTC, merged